name: Go

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run Unit Tests
      run: make test
